Fix #126: use real user id in batch jobs instead of proxy user id
Open-EO/openeo-geopyspark-driver pull request #128
Opened 2022-02-25 09:18 UTC by soxofaan

openEO processing in batch jobs needs real user id
for `load_result` and UDPs to work properly.
Proxy user id is just necessary when submitting the job.

2022-02-25 09:23 UTC, soxofaan commented
@bossie   do you think this is going to work?

2022-03-08 15:31 UTC, bossie requested changes
I would remove the "${proxyUser}" argument to batch_job.py as it is not needed.

2022-03-08 15:31 UTC, bossie commented on openeogeotrellis/deploy/batch_job.py
> +    proxy_user_id = argv[8] if len(argv) >= 9 else None
The proxy_user_id argument can be removed.

Reasoning:

The proxy user ID is only used to submit a Spark job (spark-submit --proxy-user ...) which only happens in two situations:
- explicit start job in the web API (POST '/jobs/<job_id>/results');
- asynchronously when SHub dumps batch process results in an S3 bucket and we can act on them.

So a batch job never submits batch jobs itself.

2022-03-08 15:31 UTC, bossie commented on openeogeotrellis/deploy/submit_batch_job.sh
> + "${main_py_file}" "$(basename "${processGraphFile}")" "${outputDir}" "${outputFileName}" "${userLogFileName}" "${metadataFileName}" "${apiVersion}" "${dependencies}" "${proxyUser}" "${userId}"
"${proxyUser}" argument can be removed.

2022-03-08 15:31 UTC, bossie commented on openeogeotrellis/deploy/submit_batch_job_spark24.sh
> + "${main_py_file}" "$(basename "${processGraphFile}")" "${outputDir}" "${outputFileName}" "${userLogFileName}" "${metadataFileName}" "${apiVersion}" "${dependencies}" "${proxyUser}" "${userId}"
"${proxyUser}" argument can be removed.

2022-03-08 15:31 UTC, bossie commented on openeogeotrellis/deploy/submit_batch_job_spark3.sh
> + "${main_py_file}" "$(basename "${processGraphFile}")" "${outputDir}" "${outputFileName}" "${userLogFileName}" "${metadataFileName}" "${apiVersion}" "${dependencies}" "${proxyUser}" "${userId}"
"${proxyUser}" argument can be removed.

2022-03-09 09:51 UTC, soxofaan commented
yes indeed, I didn't see `proxyUser` being used in batch_job.py, but I wanted to be sure it was fine to remove/replace it

2022-03-09 11:15 UTC, merged